baseURL = "https://diceblog.greylurk.com/"
copyright = "&copy; 2021. All Rights Reserved"
languageCode = "en-us"
title = "GM Sanctuary"
theme = "m10c"
canonifyURLs = true
publishdir = "../dist"
googleAnalytics = "G-L7VW230HL5"
disqusShortname = "gm-sanctuary"

[pagination]
  pagerSize = 5

[params]
  author = "Adam Ness"
  description = "My random thoughts on Gaming"
  avatar = "osrlogoblue.png"
  menu_item_separator = " | "
  favicon = "/favicon.ico"
  [[params.social]]
    name = "github"
    icon = "brand-github"
    url = "https://github.com/greylurk"
  [[params.social]]
    name = "bluesky"
    icon = "brand-bluesky"
    url = "https://bsky.app/profile/greylurk.bsky.social"
  [[params.social]]
    name = "x"
    icon = "brand-x"
    url = "https://x.com/greylurk"
  [[params.social]]
    name = "mastodon"
    icon = "brand-mastodon"
    url = "https://tabletop.social/@greylurk"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

