name = "Gaming Lounge"
description = "A clean, responsive, template with red accents."
license = "Apache 2.0"
licenselink = "https://github.com/tmaiaroto/hugo-redlounge/blob/master/LICENSE.md"
source_repo = "http://github.com/tmaiaroto/hugo-redlounge"
tags = ["gaming lounge", "red", "raleway", "libre baskerville", "blog", "gallery"]
features = ["blog", "gallery"]
min_version = 0.14

[author]
    name = "Adam Ness"
    homepage = "http://www.greylurk.com"
